# Theme: naysayer
# By: Brian Blakely

# Main bg
theme[main_bg]="#072626"

# Main text color
theme[main_fg]="#d3b58d"

# Title color for boxes
theme[title]="#c8d4ec"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#0fdfaf"

# Background color of selected item in processes box
theme[selected_bg]="#0a3434"

# Foreground color of selected item in processes box
theme[selected_fg]="#d3b58d"

# Color of inactive/disabled text
theme[inactive_fg]="#504038"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#90ee90"

# Cpu box outline color
theme[cpu_box]="#ffffff"

# Memory/disks box outline color
theme[mem_box]="#ffffff"

# Net up/down box outline color
theme[net_box]="#ffffff"

# Processes box outline color
theme[proc_box]="#ffffff"

# Box divider line and small boxes line color
theme[div_line]="#ffffff"

# Temperature graph colors
theme[temp_start]="#3fdf1f"
theme[temp_mid]="#ff8000"
theme[temp_end]="#800000"

# CPU graph colors
theme[cpu_start]="#3fdf1f"
theme[cpu_mid]="#ff8000"
theme[cpu_end]="#800000"

# Mem/Disk free meter
theme[free_start]="#3fdf1f"
theme[free_mid]="#ff8000"
theme[free_end]="#800000"

# Mem/Disk cached meter
theme[cached_start]="#3fdf1f"
theme[cached_mid]="#ff8000"
theme[cached_end]="#800000"

# Mem/Disk available meter
theme[available_start]="#3fdf1f"
theme[available_mid]="#ff8000"
theme[available_end]="#800000"

# Mem/Disk used meter
theme[used_start]="#3fdf1f"
theme[used_mid]="#ff8000"
theme[used_end]="#800000"

# Download graph colors
theme[download_start]="#3fdf1f"
theme[download_mid]="#ff8000"
theme[download_end]="#800000"

# Upload graph colors
theme[upload_start]="#3fdf1f"
theme[upload_mid]="#ff8000"
theme[upload_end]="#800000"

