mode = "dark"

accent = "#0fdfaf"
# This refers to "selection background"
selection = "#8fbc8f"
muted = "#a9a9a9"

background = "#072626"
dark_background = "#041818"
darker_background = "#020c0c"
lighter_background = "#0a3434"

foreground = "#d3b58d"
dark_foreground = "#a9a9a9"
light_foreground = "#c8d4ec"
bright_foreground = "#90ee90"

red = "#504038"
yellow = "#d3b58d"
orange = "#695a46"
green = "#3fdf1f"
cyan = "#0fdfaf"
blue = "#3fdf1f"
magenta = "#add8e6"
brown = "#504038"

bright_red = "#d3b58d"
bright_yellow = "#8fbc8f"
bright_green = "#90ee90"
bright_cyan = "#add8e6"
bright_blue = "#0000ff"
bright_magenta = "#ffffff"
