accent = "#0fdfaf"
cursor = "#90ee90"
foreground = "#d3b58d"
background = "#072626"
selection_foreground = "#d3b58d"
selection_background = "#0000ff"

color0 = "#041818"
color1 = "#504038"
color2 = "#3fdf1f"
color3 = "#d3b58d"
color4 = "#000080"
color5 = "#add8e6"
color6 = "#0fdfaf"
color7 = "#c8d4ec"
color8 = "#a9a9a9"
color9 = "#d3b58d"
color10 = "#90ee90"
color11 = "#b4eeb4"
color12 = "#0000ff"
color13 = "#ffffff"
color14 = "#add8e6"
color15 = "#ffffff"
